#ifndef CFG_KEYBOARD_SVAROSKEY_H
#define CFG_KEYBOARD_SVAROSKEY_H

#define CONFIG_INVERT_LAYOUT

#define CONFIG_GRID_SIZE	65
#define CONFIG_LAYOUT_SIZE	65
#define CONFIG_HW_FUNCTION_NUM	0

#endif /* CFG_KEYBOARD_SVAROSKEY_H */
