#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the svaroskey-boot_user.mk file instead.
#

# Constants automatically defined by the selected modules
svaroskey-boot_DEBUG = 1

# Our target application
TRG += svaroskey-boot

svaroskey-boot_PREFIX = "arm-none-eabi-"

svaroskey-boot_SUFFIX = ""

svaroskey-boot_SRC_PATH = svaroskey-boot

svaroskey-boot_HW_PATH = .

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey_USER_CSRC INSTEAD!
svaroskey-boot_WIZARD_CSRC = \
	bertos/cpu/cortex-m3/drv/flash_stm32.c \
	bertos/cpu/cortex-m3/drv/i2c_stm32.c \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/cpu/cortex-m3/drv/usb_stm32.c \
	bertos/cpu/cortex-m3/hw/switch_ctx_cm3.c \
	bertos/drv/eeprom.c \
	bertos/drv/i2c.c \
	bertos/drv/i2c_bitbang.c \
	bertos/drv/kbd.c \
	bertos/drv/sipo.c \
	bertos/drv/timer.c \
	bertos/drv/usbkbd.c \
	bertos/io/kblock.c \
	bertos/io/kfile.c \
	bertos/io/kfile_block.c \
	bertos/kern/proc.c \
	bertos/kern/signal.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/mware/sprintf.c \
	bertos/struct/bitarray.c \
	bertos/struct/hashtable.c \
	bertos/struct/heap.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey-boot_USER_PCSRC INSTEAD!
svaroskey-boot_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey-boot_USER_CPPASRC INSTEAD!
svaroskey-boot_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey-boot_USER_CXXSRC INSTEAD!
svaroskey-boot_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey-boot_USER_ASRC INSTEAD!
svaroskey-boot_WIZARD_ASRC = \
	 \
	#

svaroskey-boot_CPPFLAGS = -D'CPU_FREQ=(72000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(svaroskey-boot_HW_PATH) -I$(svaroskey-boot_SRC_PATH) $(svaroskey-boot_CPU_CPPFLAGS) $(svaroskey-boot_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey-boot_LDFLAGS = $(svaroskey-boot_CPU_LDFLAGS) $(svaroskey-boot_WIZARD_LDFLAGS) $(svaroskey-boot_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey-boot_CPPAFLAGS = $(svaroskey-boot_CPU_CPPAFLAGS) $(svaroskey-boot_WIZARD_CPPAFLAGS) $(svaroskey-boot_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey-boot_CSRC = $(svaroskey-boot_CPU_CSRC) $(svaroskey-boot_WIZARD_CSRC) $(svaroskey-boot_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey-boot_PCSRC = $(svaroskey-boot_CPU_PCSRC) $(svaroskey-boot_WIZARD_PCSRC) $(svaroskey-boot_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey-boot_CPPASRC = $(svaroskey-boot_CPU_CPPASRC) $(svaroskey-boot_WIZARD_CPPASRC) $(svaroskey-boot_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey-boot_CXXSRC = $(svaroskey-boot_CPU_CXXSRC) $(svaroskey-boot_WIZARD_CXXSRC) $(svaroskey-boot_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey-boot_ASRC = $(svaroskey-boot_CPU_ASRC) $(svaroskey-boot_WIZARD_ASRC) $(svaroskey-boot_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey-boot_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
svaroskey-boot_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
svaroskey-boot_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32F103RB__
svaroskey-boot_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
svaroskey-boot_PROGRAMMER_CPU = stm32
svaroskey-boot_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/stm32f103rb_rom.ld
svaroskey-boot_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
svaroskey-boot_CPU = cortex-m3
svaroskey-boot_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
svaroskey-boot_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
svaroskey-boot_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh

include $(svaroskey-boot_SRC_PATH)/svaroskey-boot_user.mk
