#include "config.h"

// Constants processed from the config file.
#define MAX_PRESSED_KEYS 10

// Stuff in memory, generated by processing config file.
static unsigned char pressed_keys_old_data[MAX_PRESSED_KEYS];
static unsigned char pressed_keys_data[MAX_PRESSED_KEYS];

// Struct we access from outside (also in eeprom memory)
static EepromConfig data = {
    .max_pressed_keys = MAX_PRESSED_KEYS,
    .pressed_keys_old = pressed_keys_old_data,
    .pressed_keys = pressed_keys_data,
    .pressed_keys_old_num = 0,
    .pressed_keys_num = 0,
};

// Exported (we get this pointer by loading the eeprom in RAM)
EepromConfig * eeprom = &data;
