#include "config.h"

// FIXME: To remove (LAYOUT_SIZE)
#include "keycodes.h"

// Constants processed from the config file.
#define MAX_PRESSED_KEYS 10

// Stuff in memory, generated by processing config file.
static unsigned char pressed_keys_old_data[MAX_PRESSED_KEYS];
static unsigned char pressed_keys_data[MAX_PRESSED_KEYS];
static unsigned char edit_buffer[MAX_PRESSED_KEYS];
static Action * actions[MAX_PRESSED_KEYS];

static Node keys[LAYOUT_SIZE] = {
    /* Row 1 */
    {{{1, ID_KEY_ESCAPE        }, 1}, 0, NULL},
    {{{1, ID_KEY_F1            }, 1}, 0, NULL},
    {{{1, ID_KEY_F2            }, 1}, 0, NULL},
    {{{1, ID_KEY_F3            }, 1}, 0, NULL},
    {{{1, ID_KEY_F4            }, 1}, 0, NULL},
    {{{1, ID_KEY_F5            }, 1}, 0, NULL},
    {{{1, ID_KEY_F6            }, 1}, 0, NULL},
    {{{1, ID_KEY_F7            }, 1}, 0, NULL},
    {{{1, ID_KEY_F8            }, 1}, 0, NULL},

    /* Row 2 */
    {{{1, ID_KEY_GRAVE         }, 1}, 0, NULL},
    {{{1, ID_KEY_1             }, 1}, 0, NULL},
    {{{1, ID_KEY_2             }, 1}, 0, NULL},
    {{{1, ID_KEY_3             }, 1}, 0, NULL},
    {{{1, ID_KEY_4             }, 1}, 0, NULL},
    {{{1, ID_KEY_5             }, 1}, 0, NULL},
    {{{1, ID_KEY_6             }, 1}, 0, NULL},
    {{{1, ID_KEY_7             }, 1}, 0, NULL},
    {{{1, ID_KEY_8             }, 1}, 0, NULL},
    {{{1, ID_KEY_9             }, 1}, 0, NULL},
    {{{1, ID_KEY_0             }, 1}, 0, NULL},

    /* Row 3 */
    {{{1, ID_KEY_TAB           }, 1}, 0, NULL},
    {{{1, ID_KEY_Q             }, 1}, 0, NULL},
    {{{1, ID_KEY_W             }, 1}, 0, NULL},
    {{{1, ID_KEY_E             }, 1}, 0, NULL},
    {{{1, ID_KEY_R             }, 1}, 0, NULL},
    {{{1, ID_KEY_T             }, 1}, 0, NULL},
    {{{1, ID_KEY_Y             }, 1}, 0, NULL},
    {{{1, ID_KEY_U             }, 1}, 0, NULL},
    {{{1, ID_KEY_I             }, 1}, 0, NULL},
    {{{1, ID_KEY_O             }, 1}, 0, NULL},

    /* Row 4 */
    {{{1, ID_KEY_CAPSLOCK      }, 1}, 0, NULL},
    {{{1, ID_KEY_A             }, 1}, 0, NULL},
    {{{1, ID_KEY_S             }, 1}, 0, NULL},
    {{{1, ID_KEY_D             }, 1}, 0, NULL},
    {{{1, ID_KEY_F             }, 1}, 0, NULL},
    {{{1, ID_KEY_G             }, 1}, 0, NULL},
    {{{1, ID_KEY_H             }, 1}, 0, NULL},
    {{{1, ID_KEY_J             }, 1}, 0, NULL},
    {{{1, ID_KEY_K             }, 1}, 0, NULL},
    {{{1, ID_KEY_L             }, 1}, 0, NULL},

    /* Row 5 */
    {{{1, ID_KEY_LEFTSHIFT     }, 1}, 0, NULL},
    {{{1, ID_KEY_Z             }, 1}, 0, NULL},
    {{{1, ID_KEY_X             }, 1}, 0, NULL},
    {{{1, ID_KEY_C             }, 1}, 0, NULL},
    {{{1, ID_KEY_V             }, 1}, 0, NULL},
    {{{1, ID_KEY_B             }, 1}, 0, NULL},
    {{{1, ID_KEY_N             }, 1}, 0, NULL},
    {{{1, ID_KEY_M             }, 1}, 0, NULL},
    {{{1, ID_KEY_COMMA         }, 1}, 0, NULL},
    {{{1, ID_KEY_PERIOD        }, 1}, 0, NULL},

    /* Row 6 */
    {{{1, ID_KEY_LEFTCONTROL   }, 1}, 0, NULL},
    {{{1, ID_KEY_LEFTGUI       }, 1}, 0, NULL},
    {{{1, ID_KEY_LEFTALT       }, 1}, 0, NULL},
    {{{1, ID_KEY_SPACE         }, 1}, 0, NULL},
    {{{1, ID_KEY_RIGHTALT      }, 1}, 0, NULL},

    /* Row 7 */
    {{{1, ID_KEY_F9            }, 1}, 0, NULL},
    {{{1, ID_KEY_F10           }, 1}, 0, NULL},
    {{{1, ID_KEY_F11           }, 1}, 0, NULL},
    {{{1, ID_KEY_F12           }, 1}, 0, NULL},
    {{{1, ID_KEY_SCROLLLOCK    }, 1}, 0, NULL},
    {{{1, ID_KEY_PRINTSCREEN   }, 1}, 0, NULL},
    {{{1, ID_KEY_PAUSE         }, 1}, 0, NULL},

    /* Row 8 */
    {{{1, ID_KEY_MINUS         }, 1}, 0, NULL},
    {{{1, ID_KEY_EQUALS        }, 1}, 0, NULL},
    {{{1, ID_KEY_DELETE        }, 1}, 0, NULL},
    {{{1, ID_KEY_INSERT        }, 1}, 0, NULL},
    {{{1, ID_KEY_HOME          }, 1}, 0, NULL},
    {{{1, ID_KEY_PAGEUP        }, 1}, 0, NULL},
    {{{1, ID_KP_NUMLOCK        }, 1}, 0, NULL},
    {{{1, ID_KP_DIVIDE         }, 1}, 0, NULL},
    {{{1, ID_KP_MULTIPLY       }, 1}, 0, NULL},
    {{{1, ID_KP_SUBTRACT       }, 1}, 0, NULL},

    /* Row 9 */
    {{{1, ID_KEY_P             }, 1}, 0, NULL},
    {{{1, ID_KEY_LEFTBRACKET   }, 1}, 0, NULL},
    {{{1, ID_KEY_RIGHTBRACKET  }, 1}, 0, NULL},
    {{{1, ID_KEY_DELETEFORWARD }, 1}, 0, NULL},
    {{{1, ID_KEY_END           }, 1}, 0, NULL},
    {{{1, ID_KEY_PAGEDOWN      }, 1}, 0, NULL},
    {{{1, ID_KP_7              }, 1}, 0, NULL},
    {{{1, ID_KP_8              }, 1}, 0, NULL},
    {{{1, ID_KP_9              }, 1}, 0, NULL},

    /* Row 10 */
    {{{1, ID_KEY_SEMICOLON     }, 1}, 0, NULL},
    {{{1, ID_KEY_QUOTE         }, 1}, 0, NULL},
    {{{1, ID_KEY_Q             }, 1}, 0, NULL},
    {{{1, ID_KEY_ENTER         }, 1}, 0, NULL},
    {{{1, ID_KEY_T             }, 1}, 0, NULL},
    {{{1, ID_KP_4              }, 1}, 0, NULL},
    {{{1, ID_KP_5              }, 1}, 0, NULL},
    {{{1, ID_KP_6              }, 1}, 0, NULL},
    {{{1, ID_KP_ADD            }, 1}, 0, NULL},

    /* Row 11 */
    {{{1, ID_KEY_SLASH         }, 1}, 0, NULL},
    {{{1, ID_KEY_BACKSLASH     }, 1}, 0, NULL},
    {{{1, ID_KEY_RIGHTSHIFT    }, 1}, 0, NULL},
    {{{1, ID_KEY_UP            }, 1}, 0, NULL},
    {{{1, ID_KP_1              }, 1}, 0, NULL},
    {{{1, ID_KP_2              }, 1}, 0, NULL},
    {{{1, ID_KP_3              }, 1}, 0, NULL},

    /* Row 12 */
    {{{1, ID_KEY_RIGHTGUI      }, 1}, 0, NULL},
    {{{1, ID_KEY_MENU          }, 1}, 0, NULL},
    {{{1, ID_KEY_RIGHTCONTROL  }, 1}, 0, NULL},
    {{{1, ID_KEY_LEFT          }, 1}, 0, NULL},
    {{{1, ID_KEY_DOWN          }, 1}, 0, NULL},
    {{{1, ID_KEY_RIGHT         }, 1}, 0, NULL},
    {{{1, ID_KP_0              }, 1}, 0, NULL},
    {{{1, ID_KP_POINT          }, 1}, 0, NULL},
    {{{1, ID_KP_ENTER          }, 1}, 0, NULL},
};

// Struct we access from outside (also in eeprom memory)
static EepromConfig data = {
    .max_pressed_keys = MAX_PRESSED_KEYS,
    .pressed_keys_old = pressed_keys_old_data,
    .pressed_keys = pressed_keys_data,
    .edit_buffer = edit_buffer,
    .pressed_keys_old_num = 0,
    .pressed_keys_num = 0,
    .actions = actions,
    .keys_num = LAYOUT_SIZE,
    .keys = keys,
};

// Exported (we get this pointer by loading the eeprom in RAM)
EepromConfig * eeprom = &data;
