#ifndef SVAROSKEY_KEYCODES_H
#define SVAROSKEY_KEYCODES_H

#include <SDL.h>

#define LAYOUT_SIZE 106

typedef uint16_t keycode_t;

#define   KEY_A                 SDL_SCANCODE_A
#define   KEY_B                 SDL_SCANCODE_B
#define   KEY_C                 SDL_SCANCODE_C
#define   KEY_D                 SDL_SCANCODE_D
#define   KEY_E                 SDL_SCANCODE_E
#define   KEY_F                 SDL_SCANCODE_F
#define   KEY_G                 SDL_SCANCODE_G
#define   KEY_H                 SDL_SCANCODE_H
#define   KEY_I                 SDL_SCANCODE_I
#define   KEY_J                 SDL_SCANCODE_J
#define   KEY_K                 SDL_SCANCODE_K
#define   KEY_L                 SDL_SCANCODE_L
#define   KEY_M                 SDL_SCANCODE_M
#define   KEY_N                 SDL_SCANCODE_N
#define   KEY_O                 SDL_SCANCODE_O
#define   KEY_P                 SDL_SCANCODE_P
#define   KEY_Q                 SDL_SCANCODE_Q
#define   KEY_R                 SDL_SCANCODE_R
#define   KEY_S                 SDL_SCANCODE_S
#define   KEY_T                 SDL_SCANCODE_T
#define   KEY_U                 SDL_SCANCODE_U
#define   KEY_V                 SDL_SCANCODE_V
#define   KEY_W                 SDL_SCANCODE_W
#define   KEY_X                 SDL_SCANCODE_X
#define   KEY_Y                 SDL_SCANCODE_Y
#define   KEY_Z                 SDL_SCANCODE_Z
#define   KEY_1                 SDL_SCANCODE_1
#define   KEY_2                 SDL_SCANCODE_2
#define   KEY_3                 SDL_SCANCODE_3
#define   KEY_4                 SDL_SCANCODE_4
#define   KEY_5                 SDL_SCANCODE_5
#define   KEY_6                 SDL_SCANCODE_6
#define   KEY_7                 SDL_SCANCODE_7
#define   KEY_8                 SDL_SCANCODE_8
#define   KEY_9                 SDL_SCANCODE_9
#define   KEY_0                 SDL_SCANCODE_0
#define   KEY_ENTER             SDL_SCANCODE_RETURN
#define   KEY_ESCAPE            SDL_SCANCODE_ESCAPE
#define   KEY_DELETE            SDL_SCANCODE_BACKSPACE
#define   KEY_TAB               SDL_SCANCODE_TAB
#define   KEY_SPACE             SDL_SCANCODE_SPACE
#define   KEY_MINUS             SDL_SCANCODE_MINUS
#define   KEY_EQUALS            SDL_SCANCODE_EQUALS
#define   KEY_LEFTBRACKET       SDL_SCANCODE_LEFTBRACKET
#define   KEY_RIGHTBRACKET      SDL_SCANCODE_RIGHTBRACKET
#define   KEY_BACKSLASH         SDL_SCANCODE_BACKSLASH
#define   KEY_SEMICOLON         SDL_SCANCODE_SEMICOLON
#define   KEY_QUOTE             SDL_SCANCODE_APOSTROPHE
#define   KEY_GRAVE             SDL_SCANCODE_GRAVE
#define   KEY_COMMA             SDL_SCANCODE_COMMA
#define   KEY_PERIOD            SDL_SCANCODE_PERIOD
#define   KEY_SLASH             SDL_SCANCODE_SLASH
#define   KEY_CAPSLOCK          SDL_SCANCODE_CAPSLOCK
#define   KEY_F1                SDL_SCANCODE_F1
#define   KEY_F2                SDL_SCANCODE_F2
#define   KEY_F3                SDL_SCANCODE_F3
#define   KEY_F4                SDL_SCANCODE_F4
#define   KEY_F5                SDL_SCANCODE_F5
#define   KEY_F6                SDL_SCANCODE_F6
#define   KEY_F7                SDL_SCANCODE_F7
#define   KEY_F8                SDL_SCANCODE_F8
#define   KEY_F9                SDL_SCANCODE_F9
#define   KEY_F10               SDL_SCANCODE_F10
#define   KEY_F11               SDL_SCANCODE_F11
#define   KEY_F12               SDL_SCANCODE_F12
#define   KEY_PRINTSCREEN       SDL_SCANCODE_PRINTSCREEN
#define   KEY_SCROLLLOCK        SDL_SCANCODE_SCROLLLOCK
#define   KEY_PAUSE             SDL_SCANCODE_PAUSE
#define   KEY_INSERT            SDL_SCANCODE_INSERT
#define   KEY_HOME              SDL_SCANCODE_HOME
#define   KEY_PAGEUP            SDL_SCANCODE_PAGEUP
#define   KEY_DELETEFORWARD     SDL_SCANCODE_DELETE
#define   KEY_END               SDL_SCANCODE_END
#define   KEY_PAGEDOWN          SDL_SCANCODE_PAGEDOWN
#define   KEY_RIGHT             SDL_SCANCODE_RIGHT
#define   KEY_LEFT              SDL_SCANCODE_LEFT
#define   KEY_DOWN              SDL_SCANCODE_DOWN
#define   KEY_UP                SDL_SCANCODE_UP
#define   KP_NUMLOCK            SDL_SCANCODE_NUMLOCKCLEAR
#define   KP_DIVIDE             SDL_SCANCODE_KP_DIVIDE
#define   KP_MULTIPLY           SDL_SCANCODE_KP_MULTIPLY
#define   KP_SUBTRACT           SDL_SCANCODE_KP_MINUS
#define   KP_ADD                SDL_SCANCODE_KP_PLUS
#define   KP_ENTER              SDL_SCANCODE_KP_ENTER
#define   KP_1                  SDL_SCANCODE_KP_1
#define   KP_2                  SDL_SCANCODE_KP_2
#define   KP_3                  SDL_SCANCODE_KP_3
#define   KP_4                  SDL_SCANCODE_KP_4
#define   KP_5                  SDL_SCANCODE_KP_5
#define   KP_6                  SDL_SCANCODE_KP_6
#define   KP_7                  SDL_SCANCODE_KP_7
#define   KP_8                  SDL_SCANCODE_KP_8
#define   KP_9                  SDL_SCANCODE_KP_9
#define   KP_0                  SDL_SCANCODE_KP_0
#define   KP_POINT              SDL_SCANCODE_KP_PERIOD
#define   KEY_NONUSBACKSLASH    SDL_SCANCODE_NONUSBACKSLASH
#define   KP_EQUALS             SDL_SCANCODE_KP_EQUALS
#define   KEY_F13               SDL_SCANCODE_F13
#define   KEY_F14               SDL_SCANCODE_F14
#define   KEY_F15               SDL_SCANCODE_F15
#define   KEY_F16               SDL_SCANCODE_F16
#define   KEY_F17               SDL_SCANCODE_F17
#define   KEY_F18               SDL_SCANCODE_F18
#define   KEY_F19               SDL_SCANCODE_F19
#define   KEY_F20               SDL_SCANCODE_F20
#define   KEY_F21               SDL_SCANCODE_F21
#define   KEY_F22               SDL_SCANCODE_F22
#define   KEY_F23               SDL_SCANCODE_F23
#define   KEY_F24               SDL_SCANCODE_F24
#define   KEY_HELP              SDL_SCANCODE_HELP
#define   KEY_MENU              SDL_SCANCODE_MENU
#define   KEY_LEFTCONTROL       SDL_SCANCODE_LCTRL
#define   KEY_LEFTSHIFT         SDL_SCANCODE_LSHIFT
#define   KEY_LEFTALT           SDL_SCANCODE_LALT
#define   KEY_LEFTGUI           SDL_SCANCODE_LGUI
#define   KEY_RIGHTCONTROL      SDL_SCANCODE_RCTRL
#define   KEY_RIGHTSHIFT        SDL_SCANCODE_RSHIFT
#define   KEY_RIGHTALT          SDL_SCANCODE_RALT
#define   KEY_RIGHTGUI          SDL_SCANCODE_RGUI

#define   ID_KEY_A              0
#define   ID_KEY_B              1
#define   ID_KEY_C              2
#define   ID_KEY_D              3
#define   ID_KEY_E              4
#define   ID_KEY_F              5
#define   ID_KEY_G              6
#define   ID_KEY_H              7
#define   ID_KEY_I              8
#define   ID_KEY_J              9
#define   ID_KEY_K              10
#define   ID_KEY_L              11
#define   ID_KEY_M              12
#define   ID_KEY_N              13
#define   ID_KEY_O              14
#define   ID_KEY_P              15
#define   ID_KEY_Q              16
#define   ID_KEY_R              17
#define   ID_KEY_S              18
#define   ID_KEY_T              19
#define   ID_KEY_U              20
#define   ID_KEY_V              21
#define   ID_KEY_W              22
#define   ID_KEY_X              23
#define   ID_KEY_Y              24
#define   ID_KEY_Z              25
#define   ID_KEY_1              26
#define   ID_KEY_2              27
#define   ID_KEY_3              28
#define   ID_KEY_4              29
#define   ID_KEY_5              30
#define   ID_KEY_6              31
#define   ID_KEY_7              32
#define   ID_KEY_8              33
#define   ID_KEY_9              34
#define   ID_KEY_0              35
#define   ID_KEY_ENTER          36
#define   ID_KEY_ESCAPE         37
#define   ID_KEY_DELETE         38
#define   ID_KEY_TAB            39
#define   ID_KEY_SPACE          40
#define   ID_KEY_MINUS          41
#define   ID_KEY_EQUALS         42
#define   ID_KEY_LEFTBRACKET    43
#define   ID_KEY_RIGHTBRACKET   44
#define   ID_KEY_BACKSLASH      45
#define   ID_KEY_SEMICOLON      46
#define   ID_KEY_QUOTE          47
#define   ID_KEY_GRAVE          48
#define   ID_KEY_COMMA          49
#define   ID_KEY_PERIOD         50
#define   ID_KEY_SLASH          51
#define   ID_KEY_CAPSLOCK       52
#define   ID_KEY_F1             53
#define   ID_KEY_F2             54
#define   ID_KEY_F3             55
#define   ID_KEY_F4             56
#define   ID_KEY_F5             57
#define   ID_KEY_F6             58
#define   ID_KEY_F7             59
#define   ID_KEY_F8             60
#define   ID_KEY_F9             61
#define   ID_KEY_F10            62
#define   ID_KEY_F11            63
#define   ID_KEY_F12            64
#define   ID_KEY_PRINTSCREEN    65
#define   ID_KEY_SCROLLLOCK     66
#define   ID_KEY_PAUSE          67
#define   ID_KEY_INSERT         68
#define   ID_KEY_HOME           69
#define   ID_KEY_PAGEUP         70
#define   ID_KEY_DELETEFORWARD  71
#define   ID_KEY_END            72
#define   ID_KEY_PAGEDOWN       73
#define   ID_KEY_RIGHT          74
#define   ID_KEY_LEFT           75
#define   ID_KEY_DOWN           76
#define   ID_KEY_UP             77
#define   ID_KP_NUMLOCK         78
#define   ID_KP_DIVIDE          79
#define   ID_KP_MULTIPLY        80
#define   ID_KP_SUBTRACT        81
#define   ID_KP_ADD             82
#define   ID_KP_ENTER           83
#define   ID_KP_1               84
#define   ID_KP_2               85
#define   ID_KP_3               86
#define   ID_KP_4               87
#define   ID_KP_5               88
#define   ID_KP_6               89
#define   ID_KP_7               90
#define   ID_KP_8               91
#define   ID_KP_9               92
#define   ID_KP_0               93
#define   ID_KP_POINT           94
#define   ID_KEY_NONUSBACKSLASH 95
#define   ID_KP_EQUALS          96
#define   ID_KEY_F13            97
#define   ID_KEY_F14            98
#define   ID_KEY_F15            99
#define   ID_KEY_F16            100
#define   ID_KEY_F17            101
#define   ID_KEY_F18            102
#define   ID_KEY_F19            103
#define   ID_KEY_F20            104
#define   ID_KEY_F21            105
#define   ID_KEY_F22            106
#define   ID_KEY_F23            107
#define   ID_KEY_F24            108
#define   ID_KEY_HELP           109
#define   ID_KEY_MENU           110
#define   ID_KEY_LEFTCONTROL    111
#define   ID_KEY_LEFTSHIFT      112
#define   ID_KEY_LEFTALT        113
#define   ID_KEY_LEFTGUI        114
#define   ID_KEY_RIGHTCONTROL   115
#define   ID_KEY_RIGHTSHIFT     116
#define   ID_KEY_RIGHTALT       117
#define   ID_KEY_RIGHTGUI       118

// Remember to add any additional key into the keycodes array below!

extern keycode_t keycodes[];
extern size_t keycodes_count;

#endif /* SVAROSKEY_KEYCODES_H */
