/**
 * \file
 * <!--
 * Copyright 2018 Daniele Basile <asterix24@gmail.com>
 * All Rights Reserved.
 * -->
 *
 * \brief Keyboard Map
 *
 * \author Daniele Basile <asterix24@gmail.com>
 */

#include "hw/keyboard_map.h"
#include "hw/hw_keymap.h"
#include "cfg/cfg_keymap.h"

KeyMap keyboard_layout[] = {
#if CFG_KEYBOARD_LAYOUT == KEYBOARD_PETROSKEY_LAYOUT
	// Row 1
	{ COL0,  KEY_PORTB, ROW0, KEY_PORTC }, // K1
	{ COL1,  KEY_PORTB, ROW0, KEY_PORTC }, // K2
	{ COL2,  KEY_PORTB, ROW0, KEY_PORTC }, // K3
	{ COL3,  KEY_PORTB, ROW0, KEY_PORTC }, // K4
	{ COL4,  KEY_PORTB, ROW0, KEY_PORTC }, // K5
	{ COL5,  KEY_PORTB, ROW0, KEY_PORTC }, // K6
	{ COL6,  KEY_PORTB, ROW0, KEY_PORTC }, // K7
	{ COL7,  KEY_PORTB, ROW0, KEY_PORTC }, // K8
	{ COL8,  KEY_PORTB, ROW0, KEY_PORTC }, // K9
	{ COL9,  KEY_PORTB, ROW0, KEY_PORTC }, // K10
	{ COL10, KEY_PORTB, ROW0, KEY_PORTC }, // K11
	{ COL11, KEY_PORTB, ROW0, KEY_PORTC }, // K12

	// Row 2
	{ COL0,  KEY_PORTB, ROW1, KEY_PORTC }, // K13
	{ COL1,  KEY_PORTB, ROW1, KEY_PORTC }, // K14
	{ COL2,  KEY_PORTB, ROW1, KEY_PORTC }, // K15
	{ COL3,  KEY_PORTB, ROW1, KEY_PORTC }, // K16
	{ COL4,  KEY_PORTB, ROW1, KEY_PORTC }, // K17
	{ COL5,  KEY_PORTB, ROW1, KEY_PORTC }, // K18
	{ COL6,  KEY_PORTB, ROW1, KEY_PORTC }, // K19
	{ COL7,  KEY_PORTB, ROW1, KEY_PORTC }, // K20
	{ COL8,  KEY_PORTB, ROW1, KEY_PORTC }, // K21
	{ COL9,  KEY_PORTB, ROW1, KEY_PORTC }, // K22
	{ COL10, KEY_PORTB, ROW1, KEY_PORTC }, // K23
	{ COL11, KEY_PORTB, ROW1, KEY_PORTC }, // K24

	// Row 3
	{ COL0,  KEY_PORTB, ROW2, KEY_PORTC }, // K25
	{ COL1,  KEY_PORTB, ROW2, KEY_PORTC }, // K26
	{ COL2,  KEY_PORTB, ROW2, KEY_PORTC }, // K27
	{ COL3,  KEY_PORTB, ROW2, KEY_PORTC }, // K28
	{ COL4,  KEY_PORTB, ROW2, KEY_PORTC }, // K29
	{ COL5,  KEY_PORTB, ROW2, KEY_PORTC }, // K30
	{ COL6,  KEY_PORTB, ROW2, KEY_PORTC }, // K31
	{ COL7,  KEY_PORTB, ROW2, KEY_PORTC }, // K32
	{ COL8,  KEY_PORTB, ROW2, KEY_PORTC }, // K33
	{ COL9,  KEY_PORTB, ROW2, KEY_PORTC }, // K34
	{ COL10, KEY_PORTB, ROW2, KEY_PORTC }, // K35
	{ COL11, KEY_PORTB, ROW2, KEY_PORTC }, // K36

	// Row 4
	{ COL0,  KEY_PORTB, ROW3, KEY_PORTC }, // K37
	{ COL1,  KEY_PORTB, ROW3, KEY_PORTC }, // K38
	{ COL2,  KEY_PORTB, ROW3, KEY_PORTC }, // K39
	{ COL3,  KEY_PORTB, ROW3, KEY_PORTC }, // K40
	{ COL4,  KEY_PORTB, ROW3, KEY_PORTC }, // K41
	{ COL5,  KEY_PORTB, ROW3, KEY_PORTC }, // K42
	{ COL6,  KEY_PORTB, ROW3, KEY_PORTC }, // K43
	{ COL7,  KEY_PORTB, ROW3, KEY_PORTC }, // K44
	{ COL8,  KEY_PORTB, ROW3, KEY_PORTC }, // K45
	{ COL9,  KEY_PORTB, ROW3, KEY_PORTC }, // K46
	{ COL10, KEY_PORTB, ROW3, KEY_PORTC }, // K47
	{ COL11, KEY_PORTB, ROW3, KEY_PORTC }, // K48

	// Row 5
	{ COL0,  KEY_PORTB, ROW4, KEY_PORTC }, // K49
	{ COL1,  KEY_PORTB, ROW4, KEY_PORTC }, // K50
	{ COL2,  KEY_PORTB, ROW4, KEY_PORTC }, // K51
	{ COL3,  KEY_PORTB, ROW4, KEY_PORTC }, // K52
	{ COL4,  KEY_PORTB, ROW4, KEY_PORTC }, // K53
	{ COL5,  KEY_PORTB, ROW4, KEY_PORTC }, // K54
	{ COL6,  KEY_PORTB, ROW4, KEY_PORTC }, // K55
	{ COL7,  KEY_PORTB, ROW4, KEY_PORTC }, // K56
	{ COL8,  KEY_PORTB, ROW4, KEY_PORTC }, // K57
	{ COL9,  KEY_PORTB, ROW4, KEY_PORTC }, // K58
	{ COL10, KEY_PORTB, ROW4, KEY_PORTC }, // K59
	{ COL11, KEY_PORTB, ROW4, KEY_PORTC }, // K60

	// Row 6
	{ COL0,  KEY_PORTB, ROW5, KEY_PORTC }, // K61
	{ COL1,  KEY_PORTB, ROW5, KEY_PORTC }, // K62
	{ COL2,  KEY_PORTB, ROW5, KEY_PORTC }, // K63
	{ COL3,  KEY_PORTB, ROW5, KEY_PORTC }, // K64
	{ COL4,  KEY_PORTB, ROW5, KEY_PORTC }, // K65
#else
	#error No layout defined

#endif
};

