#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the svaroskey_user.mk file instead.
#

# Constants automatically defined by the selected modules
svaroskey_DEBUG = 1

# Our target application
TRG += svaroskey

svaroskey_PREFIX = "arm-none-eabi-"

svaroskey_SUFFIX = ""

svaroskey_SRC_PATH = svaroskey

svaroskey_HW_PATH = svaroskey

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey_USER_CSRC INSTEAD!
svaroskey_WIZARD_CSRC = \
	bertos/cpu/cortex-m3/drv/flash_stm32.c \
	bertos/cpu/cortex-m3/drv/i2c_stm32.c \
	bertos/cpu/cortex-m3/drv/timer_cm3.c \
	bertos/cpu/cortex-m3/drv/usb_stm32.c \
	bertos/cpu/cortex-m3/hw/switch_ctx_cm3.c \
	bertos/drv/eeprom.c \
	bertos/drv/i2c.c \
	bertos/drv/i2c_bitbang.c \
	bertos/drv/kbd.c \
	bertos/drv/sipo.c \
	bertos/drv/timer.c \
	bertos/drv/usbkbd.c \
	bertos/io/kblock.c \
	bertos/io/kfile.c \
	bertos/io/kfile_block.c \
	bertos/kern/proc.c \
	bertos/kern/signal.c \
	bertos/mware/cli.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/mware/parser.c \
	bertos/mware/readline.c \
	bertos/mware/sprintf.c \
	bertos/struct/bitarray.c \
	bertos/struct/hashtable.c \
	bertos/struct/heap.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey_USER_PCSRC INSTEAD!
svaroskey_WIZARD_PCSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey_USER_CPPASRC INSTEAD!
svaroskey_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey_USER_CXXSRC INSTEAD!
svaroskey_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE svaroskey_USER_ASRC INSTEAD!
svaroskey_WIZARD_ASRC = \
	 \
	#

svaroskey_CPPFLAGS = -D'CPU_FREQ=(72000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(svaroskey_HW_PATH) -I$(svaroskey_SRC_PATH) $(svaroskey_CPU_CPPFLAGS) $(svaroskey_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey_LDFLAGS = $(svaroskey_CPU_LDFLAGS) $(svaroskey_WIZARD_LDFLAGS) $(svaroskey_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey_CPPAFLAGS = $(svaroskey_CPU_CPPAFLAGS) $(svaroskey_WIZARD_CPPAFLAGS) $(svaroskey_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey_CSRC = $(svaroskey_CPU_CSRC) $(svaroskey_WIZARD_CSRC) $(svaroskey_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey_PCSRC = $(svaroskey_CPU_PCSRC) $(svaroskey_WIZARD_PCSRC) $(svaroskey_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey_CPPASRC = $(svaroskey_CPU_CPPASRC) $(svaroskey_WIZARD_CPPASRC) $(svaroskey_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey_CXXSRC = $(svaroskey_CPU_CXXSRC) $(svaroskey_WIZARD_CXXSRC) $(svaroskey_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey_ASRC = $(svaroskey_CPU_ASRC) $(svaroskey_WIZARD_ASRC) $(svaroskey_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
svaroskey_CPU_CPPASRC = bertos/cpu/cortex-m3/hw/crt_cm3.S bertos/cpu/cortex-m3/hw/vectors_cm3.S 
svaroskey_CPU_CPPAFLAGS = -g -gdwarf-2 -mthumb -mno-thumb-interwork
svaroskey_CPU_CPPFLAGS = -O0 -g3 -gdwarf-2 -mthumb -mno-thumb-interwork -fno-strict-aliasing -fwrapv -fverbose-asm -Ibertos/cpu/cortex-m3/ -D__ARM_STM32F103RB__
svaroskey_CPU_CSRC = bertos/cpu/cortex-m3/hw/init_cm3.c bertos/cpu/cortex-m3/drv/irq_cm3.c bertos/cpu/cortex-m3/drv/gpio_stm32.c bertos/cpu/cortex-m3/drv/clock_stm32.c 
svaroskey_PROGRAMMER_CPU = stm32
svaroskey_CPU_LDFLAGS = -mthumb -mno-thumb-interwork -nostartfiles -Wl,--no-warn-mismatch -Wl,-dT bertos/cpu/cortex-m3/scripts/stm32f103rb_rom.ld
svaroskey_STOPFLASH_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
svaroskey_CPU = cortex-m3
svaroskey_STOPDEBUG_SCRIPT = bertos/prg_scripts/arm/stopopenocd.sh
svaroskey_DEBUG_SCRIPT = bertos/prg_scripts/arm/debug.sh
svaroskey_FLASH_SCRIPT = bertos/prg_scripts/arm/flash-stm32.sh

include $(svaroskey_SRC_PATH)/svaroskey_user.mk
